version: '3'

services:

  webpage-service:
    build: ./webpage-service
    ports:
      - 8080:80
    depends_on:
      - chat-api

  chat-api:
    build: ./chat-service/api
    volumes:
      - ./chat-service/api:/usr/src/app